theme: jekyll-theme-midnight
title: Nighthawk CSA
gitorg: "https://github.com/nighthawkcoders"
description: "This GitHub project provides Advance Placement Computer Science 'A' (AP-CSA) code, training, and teaching materials.  This page is a 'GitHub Pages' website and contains guidance and development activities.   Cloning the GitHub Project provides Java-Spring webserver code.  Explore this page for activities. including procedures to develop, build, and deploy a Web Server."
webserver: "https://csa.nighthawkcodingsociety.com/"
webserverid: "nighthawkcodingsociety"
twitter: "https://twitter.com/NighthawkCoding"
twitterid: "@NighthawkCoding"
email: "nighthawkcodingsociety@gmail.com"
