version: '3'
services:
  web:
    image: java_csav2
    build: .
    ports:
      - "8081:8080"
    volumes:
      - persistent_volume:/app/volumes
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/nighthawk_csa/volumes
